import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState({list: [{name: '', points: 0, price: 0, tokenAddress: '', solPerPoints: 0}]})
  const [isLoading, setLoading] = useState(false)
  const [route, setRoute] = useState(String)
  const [totalSpent, setTotalSpent] = useState(0)
  const [totalPoints, setTotalPoints] = useState(0)
  let ts = 0
  let tp = 0
  const handleSubmit = (e: { preventDefault: () => void }) => {
      e.preventDefault()
      setLoading(true)
      fetch('/api/points', {method: 'POST', body: JSON.stringify(route)})
        .then((res) => res.json())
        .then((data) => {
          for(const n of data.list){
            ts += n.price
            tp += n.points
          }
          setTotalPoints(tp)
          setTotalSpent(ts)
          setData(data)
          setLoading(false)
        })
  }

  if (isLoading) return <div className={styles.main}><h2 className={styles.center}>Loading...</h2></div>
  if(data.list[0].name!='') return <div key={`main-div`} className={styles.main}>
    <div key={`sub-div`}>
      <button key={`button`} type="button" className={styles.boton}><Link href="https://frakt-points-amni9vu27-crypto-tio-sam.vercel.app/">Back</Link></button>
      <h2 key={`h2`} className={styles.center}>You have to spent {totalSpent} SOL for {totalPoints} points</h2> 
      <div key={`grid-div`} className={styles.grid}>
        {data.list.map((nft, index)=>{
          const href = `https://hyperspace.xyz/token/${nft.tokenAddress}`
          return <div key={`card-${index}`} className={styles.card}>
            <a key={`name-${index}`} href={href} className={styles.description}>Name: {nft.name}</a>
            <div key={`points-${index}`} className={styles.description}>Points: {nft.points}</div> 
            <p key={`price-${index}`} className={styles.description}>Price: {nft.price}</p> 
            <p key={`solperpoint-${index}`} className={styles.description}>Sol/Points: {nft.solPerPoints}</p> 
          </div>
        })}
      </div>
    </div>
  </div>
  return (
    <>
    <Head>
      <title>FRAKT BEST DEALS</title>
      <meta name="description" content="Generated by @CryptoTioSam" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <h2>
          <a href="https://twitter.com/CryptoTioSam" target="_blank" rel="noopener noreferrer">
            By{' @CryptoTioSam '}
          </a>
        </h2>
        <div>
          <div className={styles.description}>
              <form className={styles.description} onSubmit={handleSubmit}>
                <label htmlFor="points">Points needed </label>
                <input type="text" name='route' onChange={(e)=>{setRoute(e.target.value)}}/>
                <button type="submit" className={styles.boton}>Submit</button>
              </form>
          </div>
        </div>
      </div>
      
    </main>
    
  </>
  )
}
